language: rust
rust:
  - stable
os:
  - linux
  - osx

dist: trusty
sudo: false

cache: cargo

branches:
  only:
    # Release tags
    - /^v\d+\.\d+\.\d+.*$/
    - test-release-tag-please-ignore
    - master
    - develop
    - travis
    - staging

script:
  - cargo test --release --verbose
  -  "./misc/download-gum-corpus.sh"
  - cargo build --verbose --release 
  - ./target/release/annis data --cmd 'import relannis/GUM'
  - cargo test --release --verbose  -- --ignored

before_deploy:
  - export RELEASE_PKG_FILE=target/release/libgraphannis_capi.so
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export RELEASE_PKG_FILE=target/release/libgraphannis_capi.dylib ; fi


deploy:
  provider: releases
  api_key:
    secure: "VZxMx6T27LnD2Y8PIXzSMuTE+bfBRo+FyxEyZ/tcDwWYttcU9fNtHuD96sIooNifdup1aiW4hMYkOfjGEqMhzymJIflT+rWms4EmljxTG45XJivooak+oe2T4wQvELBSH3ejmQxD5Zyvjn/i3ifOIbpJAMVPqSwjkHSnyXwWk2ARX35XIpa40XLi1T3fsrQmeH4JAFSdlCnsF6AelacwwbwtPudZHnTh795oIBEnAtihcmKClLCE8OV7pP8kaDISvHoKsHly5wmBTzxpQh7P8srIRCQjYxU/e4LBlS8NiIcz1h5ca9htV3wZKbJgoOIGiVB+FsCRJtdwGmk6IiF8pB6D8A3mI+EUxcJvmFKIzc83IcqulPs3S0XrsdwHT7TA/uBScOBhbLbx1VtU8lhMvfGKdo74Jx2NU9XeaNr+ptM0ewMxqL3zjITKjEDsO1OrLbcGnpCfswSfFV+TgLHw7wEOdRbRzWSdhROFUEZ2tW6GIfFVwtrLUPXs2ikW5H/8Ja/QV2v0joHqLbGvMZD13RpiRJdziQQANQPsfs8i59B7zrrP7/BwRr9lLP8kABIZ/e2bHGZJJH57jmt/QR5Aa445L/K5g1uC0vLcj7epUVcHcgiZakW1ZNX8o8fCOLJKkO9xB9qEKH6KfdZc09+yxdEsTs1w7HBYuE0LqRuvdek="
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  on:
    repo: corpus-tools/graphANNIS
    branch: master
    tags: true
  skip_cleanup: true
  tag_name: $TRAVIS_TAG
  draft: true