language: cpp
os:
  - linux
  - osx

dist: trusty
sudo: false

addons:
  apt:
   packages:
    - libboost-dev
    - libboost-thread-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libicu-dev
    - maven
    - wget

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install icu4c maven wget ; fi

script:
 - ./download-gum-corpus.sh
 - mkdir build
 - cd build/
 - cmake ..
 - make
 - cd ..
 - ./build/annis_runner import ../relannis/GUM ../data/GUM
 - ./build/test_graphANNIS --gtest_filter="SearchTestGUM.*:CorpusStorageManagerTest.*"
 - mvn test
