upload-doc = false
sign-commit = true
dev-version-ext = "dev"
pre-release-hook = ["cargo", "test"]
pre-release-replacements = [ 
    {file="CHANGELOG.md", search="## \\[Unreleased\\]", replace="## [Unreleased]\n\n## [{{version}}] - {{date}}"},
    {file="CITATION.cff", search="version: [0-9.]+", replace="version: {{version}}"}, 
    {file="CITATION.cff", search="date-released: [0-9\\-]+", replace="date-released: {{date}}"}, 
    {file="docs/src/embed-rust.md", search="graphannis = \"[0-9.]+\"", replace="graphannis = \"{{version}}\""}
]
