[package]
name = "graphannis"
version = "0.1.0" #:version
authors = ["Thomas Krause <thomaskrause@posteo.de>"]

workspace = ".."

[lib]

[dependencies]
regex = "0.2"
regex-syntax = "0.5"
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
rand = "0.4"
csv = "1.0.0-beta.5"
multimap = "0.4"
log = "0.4"
lazy_static = "1.0"
strum = "*"
strum_macros = "*"
serde_json = "1.0"
num = "0.1"
heapsize = "0.4"
heapsize_derive = "0.1"
linked-hash-map = "0.5"
tempdir = "0.3"
itertools = "0.7"
