[package]
name = "graphannis"
version = "0.26.0"
authors = ["Thomas Krause <thomaskrause@posteo.de>"]
license = "Apache-2.0"
description = "This is a new backend implementation of the ANNIS linguistic search and visualization system."
repository = "https://github.com/korpling/graphANNIS"
readme = "crate-info.md"
build = "build.rs"
edition = "2018"

[lib]
crate-type = ["lib"]

[build-dependencies]
lalrpop = { version = "0.18", features = ["lexer"] }
csv = "1"
regex = "1"
file_diff = "1"

[dependencies]
graphannis-core = { path = "../core/" }
regex = "1"
regex-syntax = "0.6"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
rand = { version = "0.7", features = ["small_rng"] }
csv = "1"
log = "0.4"
lazy_static = "1.4"
linked-hash-map = "0.5"
itertools = "0.8"
rustc-hash = "1.0"
rayon = { version = "1.3", default-features = false }
sys-info = ">= 0.5.8, < 0.5.9"
fs2 = "0.4"
lalrpop-util = "0.18"
boolean_expression = "0.3"
percent-encoding = "1.0"
libc = "0.2"
anyhow = "1"
graphannis-malloc_size_of = "1.0"
graphannis-malloc_size_of_derive = "2.0"
strum = "0.18"
strum_macros = "0.18"

[target.'cfg(windows)'.dependencies]
kernel32-sys = { version = "0.2.2" }

[dev-dependencies]
tempfile = "3"
criterion = "0.3"

[[bench]]
name = "graphannis"
harness = false
