[package]
name = "graphannis"
version = "0.7.0" #:version
authors = ["Thomas Krause <thomaskrause@posteo.de>"]

license = "Apache-2.0"
description = "This is a prototype for a new backend implementation of the ANNIS linguistic search and visualization system."
repository= "https://github.com/thomaskrause/graphANNIS"
readme = "../README.md"

workspace = ".."

[lib]

[dependencies]
regex = "1.0"
regex-syntax = "0.6"
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
rand = "0.4"
csv = "1.0.0-beta.5"
multimap = "0.4"
log = "0.4"
lazy_static = "1.0"
strum = "0.9"
strum_macros = "0.9"
serde_json = "1.0"
num = "0.1"
heapsize = "0.4"
heapsize_derive = "0.1"
linked-hash-map = "0.5"
tempdir = "0.3"
itertools = "0.7"
fxhash = "0.2"
rayon = "1.0"
malloc_size_of = { path = "../ext/malloc_size_of" }
malloc_size_of_derive = { path = "../ext/malloc_size_of_derive" }
jemalloc-sys = "0.1"
libc = "0.2"

[dev-dependencies]
bencher = "0.1"

[[bench]]
name = "graphannis"
harness = false