[package]
name = "graphannis-tutorial"
version = "0.31.1"
authors = ["Thomas Krause <thomaskrause@posteo.de>"]
edition = "2018"
publish = false

[dependencies]
graphannis =  { path = "../../graphannis" }
