[package]
name = "graphannis-capi"
version = "0.27.0"
authors = ["Thomas Krause <thomaskrause@posteo.de>"]
license = "Apache-2.0"
description = "This is the C-API to the ANNIS linguistic search and visualization system."
repository = "https://github.com/korpling/graphANNIS"
readme = "crate-info.md"
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
graphannis = { path = "../graphannis/", version = "^0.27" }
simplelog = { version = "0.7"}
log = "0.4"
libc = "0.2"
