[package]
name = "graphannis-capi"
version = "0.1.0"
authors = ["Thomas Krause <thomaskrause@posteo.de>"]

workspace = ".."

[lib]
crate-type = ["staticlib","cdylib"]

[dependencies]
graphannis = {path = "../graphannis"}
simplelog = "0.5"
log = "0.4"

libc = "0.2"
